export interface JftResource {
  id: string;
  title: string;
  link: string;
  password: string;
  type: "mocktest" | "coupon" | "kanji" | "class" | "pdf" | "listening" | "expression";
  note: string;
  priority: "high" | "medium" | "low";
}

export const jftResources: JftResource[] = [
  {
    id: "mt-1",
    title: "MockTest- 1",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSeuoXNg9F4uPLaDEwmIZCDI76GJHq540a5omZp9CQPF5lt4eg/viewform?usp=header",
    password: "irodoribhai1",
    type: "mocktest",
    note: "পাসওয়ার্ড: irodoribhai1",
    priority: "high",
  },
  {
    id: "mt-16",
    title: "MockTest - 16",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSeG-CHoQbBSwScJhHEeyN_biq_yjF9Cv_b4XAEe35Uhyz2DKQ/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "জুলাই মাসের পরীক্ষার্থীদের জন্য গুরুত্বপূর্ণ",
    priority: "high",
  },
  {
    id: "mt-2",
    title: "Mocktest 2",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSf45gxgU7F-uMKpdwgEnV46Mt9Qf6b4u8iPUuAO1nOAf8pj9Q/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "সন্ধ্যা ৭ টার আগে দিন",
    priority: "high",
  },
  {
    id: "mt-3",
    title: "Mocktest-3",
    link: "https://forms.gle/SNp5tSn246wcHwBXA",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "coupon-1",
    title: "কুপন টেস্ট",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSdN1UVrFXCOjvtHzoail27CsSmTruft1Hnm7cvLBFuRyk7pSw/viewform?chromeless=1",
    password: "irodoribhai1",
    type: "coupon",
    note: "কুপন শেখানো হবে",
    priority: "high",
  },
  {
    id: "coupon-2",
    title: "Cupon Test -2",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfywu7DHCcC0KgdAuCZGkEbGJWth1z5KBHT3OpkysMl89OvzQ/viewform?usp=header",
    password: "irodoribhai1",
    type: "coupon",
    note: "",
    priority: "high",
  },
  {
    id: "coupon-3",
    title: "কুপন টেস্ট- ৩",
    link: "https://forms.gle/L7ocdQnfvmw6F7vK9",
    password: "",
    type: "coupon",
    note: "পাসওয়ার্ড লাগবে না",
    priority: "high",
  },
  {
    id: "mt-5",
    title: "MockTest ৫",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSf1zYojYJJDTUWF8yN-I9z7sQ7KdOPPu9ljvdvZRb1fkG4x6A/viewform?fbzx=-2002065225803381673",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-6",
    title: "Mocktest- 6",
    link: "https://docs.google.com/forms/d/e/1FAIpQLScm35Ab90Cud3cTrtaDvVaDC9v-V_Np1iHjuWJb-AX7pSgWYg/viewform?fbzx=708441587961218692",
    password: "irodoribhaibatch-1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-7",
    title: "MockTest- 7",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfdvXFWN8VCQKD5mI50OvPMscU-BoKQZ8TADDtTK210_L1HSA/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-8",
    title: "MockTest - 8",
    link: "https://forms.gle/S5Mv166j559qWaNq9",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-9",
    title: "Mocktest- 9",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfzX-XK67B5X3pUTti7kao12uYK1pGFlGl6lC_AHSYI3d5p7w/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-10",
    title: "মকটেষ্ট - ১০",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSc_bYBIelIglRhMhSqQgaGGpdZ3XkRmG3MwUfPEFrwbxUBTKQ/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-11",
    title: "মক টেস্ট- ১১",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSdciIGaSf-PM3ytYhDfk4Sy_rElvZZ1i5OCPqU6gsfwCzW10Q/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-12",
    title: "মকটেস্ট - ১২",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSekkN1pgMVl5MmxXK3qXJB0ZJj5NHwCmqBA4iPmT20QUKoLLQ/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-13",
    title: "MockTest 13",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSdIIoCHvnnk-L_0LGkLCXsr4PRrbuq_wALb_0S_9-jwKyXsrQ/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-14",
    title: "Mocktest- 14",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSextnkNiUKHHeXhxqSoP0t9HDjusfHOZu-wASuR4PU_2I7WSQ/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "জুলাই মাসের পরীক্ষার্থীদের জন্য গুরুত্বপূর্ণ",
    priority: "high",
  },
  {
    id: "mt-15",
    title: "Mocktest- 15",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfPo7tMqweOApzJFMqG0OLvGmQltTcW7m1sYerfj97Tzgp0yw/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "জুলাই মাসের পরীক্ষার্থীদের জন্য গুরুত্বপূর্ণ",
    priority: "high",
  },
  {
    id: "mt-17",
    title: "Mocktest- 17",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSeDaC-nZkFtRYPbFJvXN_8q5aKxVV5UV-siTVsiLqnlaFNNgQ/viewform?fbzx=-5261558040964941299",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-18",
    title: "Mock test - 18",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSeM5MKOxI3VrXA5xKZ2n72AQgBX-NTJ7XttilD0kgkCq3tv6w/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-19",
    title: "Mocktest- 19",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSei0IFIkaLQtpPKt_xEy_FGXkxaZ0PKNTckwrgLxXAWUhNm7A/viewform?fbzx=-6755156405477424518",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-21",
    title: "মকটেস্ট ২১",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSeHjlkciF-4n1NxNt0w-5QniS97C7DRWW6JOCHX_ojMoMAErQ/viewform",
    password: "irodoribhai1",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-22",
    title: "মকটেস্ট ২২",
    link: "https://22-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "খুব গুরুত্বপূর্ণ, প্রতিটি প্রশ্ন মুখস্থ",
    priority: "high",
  },
  {
    id: "mt-23",
    title: "মকটেস্ট ২৩",
    link: "https://23-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "গতকালের মতো গুরুত্বপূর্ণ",
    priority: "high",
  },
  {
    id: "mt-24",
    title: "মক টেস্ট ২৪",
    link: "https://24-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "আপডেট",
    priority: "high",
  },
  {
    id: "mt-25",
    title: "মকটেস্ট ২৫",
    link: "https://25-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "লিসেনিং ব্রাউজার সমস্যা হলে মজিলা ব্যবহার করুন",
    priority: "high",
  },
  {
    id: "mt-26",
    title: "মকটেস্ট ২৬",
    link: "https://26-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "Mozilla Firefox ব্যবহার করুন",
    priority: "high",
  },
  {
    id: "mt-27",
    title: "২৭ নাম্বার মক টেস্ট",
    link: "https://27-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "",
    priority: "high",
  },
  {
    id: "mt-28",
    title: "মকটেস্ট ২৮ (পরিবর্তিত)",
    link: "https://28-mocktest-irodorivai.netlify.app/",
    password: "",
    type: "mocktest",
    note: "গতকালের পরিবর্তিত",
    priority: "high",
  },
  {
    id: "xbook-l13",
    title: "X book Lesson 13 Mocktest",
    link: "https://forms.office.com/pages/responsepage.aspx?id=oy_HkJxhhky73GK1b_fZOWCUYNw6LTpHr9kYeH6jXspUQTczRFo4VEM0NUpLOFYyMEY2Sk9XQzVNTCQlQCN0PWcu&route=shorturl",
    password: "",
    type: "mocktest",
    note: "X book লেসন ১৩ ভিত্তিক মকটেস্ট",
    priority: "high",
  },
  {
    id: "xbook-l14",
    title: "X book Lesson 14 Mocktest",
    link: "https://forms.office.com/pages/responsepage.aspx?id=oy_HkJxhhky73GK1b_fZOWCUYNw6LTpHr9kYeH6jXspUQUFHMldLUkhBQlZMTzI3TEcxOVBFTEVTRSQlQCN0PWcu&route=shorturl",
    password: "",
    type: "mocktest",
    note: "X book লেসন ১৪ ভিত্তিক মকটেস্ট",
    priority: "high",
  },
  {
    id: "xbook-l15",
    title: "X book Lesson 15 Mocktest",
    link: "https://forms.office.com/pages/responsepage.aspx?id=oy_HkJxhhky73GK1b_fZOWCUYNw6LTpHr9kYeH6jXspUM0MxOFBUSUtZTVA0WVJBTkFPQVBIVDFSSiQlQCN0PWcu&route=shorturl",
    password: "",
    type: "mocktest",
    note: "X book লেসন ১৫ ভিত্তিক মকটেস্ট",
    priority: "high",
  },
  {
    id: "xbook-l16",
    title: "X book Lesson 16 Mocktest",
    link: "https://forms.office.com/pages/responsepage.aspx?id=oy_HkJxhhky73GK1b_fZOWCUYNw6LTpHr9kYeH6jXspUNVc1SFU3V0VSNVIwWDFKS1BXTUlIRlcxUyQlQCN0PWcu&route=shorturl",
    password: "",
    type: "mocktest",
    note: "X book লেসন ১৬ ভিত্তিক মকটেস্ট",
    priority: "high",
  },
  {
    id: "xbook-l17",
    title: "X book Lesson 17 Mocktest",
    link: "https://forms.office.com/pages/responsepage.aspx?id=oy_HkJxhhky73GK1b_fZOWCUYNw6LTpHr9kYeH6jXspUOTdLMVBLWDk2QjBHNUsyVTJSTjU3WDA1NCQlQCN0PWcu&route=shorturl",
    password: "",
    type: "mocktest",
    note: "X book লেসন ১৭ ভিত্তিক মকটেস্ট",
    priority: "high",
  },
  {
    id: "xbook-l18",
    title: "X book Lesson 18 Mocktest",
    link: "https://forms.office.com/pages/responsepage.aspx?id=oy_HkJxhhky73GK1b_fZOWCUYNw6LTpHr9kYeH6jXspUMjA5MzJZWFNVNUhBTFZHWUhCR0RMODdXTCQlQCN0PWcu&route=shorturl",
    password: "",
    type: "mocktest",
    note: "X book লেসন ১৮ ভিত্তিক মকটেস্ট",
    priority: "high",
  },
  {
    id: "cls-xyz-grammar",
    title: "X, Y, Z Grammar Solution",
    link: "https://www.youtube.com/watch?v=nxNC1_0AqO4&list=PLvsHTr2JeNs3JUMsXVSsLPXiHl6LQy3bL",
    password: "",
    type: "class",
    note: "Playlist",
    priority: "medium",
  },
  {
    id: "cls-xyz-expression",
    title: "X,Y,Z Expression solution",
    link: "https://youtube.com/playlist?list=PLvsHTr2JeNs3dyZET_Lzdqef64y7hBJHj&si=dnjDPVSXbYRW8TGV",
    password: "",
    type: "class",
    note: "Playlist",
    priority: "medium",
  },
  {
    id: "cls-mock-solution",
    title: "সকল মক্টেস্ট সমাধান ক্লাস",
    link: "https://youtube.com/playlist?list=PLvsHTr2JeNs1Dwgp209wGAQvvzpB2iRaz&si=XyEeFf2X5-zeOMs2",
    password: "",
    type: "class",
    note: "Playlist",
    priority: "medium",
  },
  {
    id: "cls-chapter-mini",
    title: "অধ্যায়ভিত্তিক মিনি মকটেস্ট",
    link: "https://youtube.com/playlist?list=PLvsHTr2JeNs1QHEAUCctnJj-7MO1Wunr3&si=k0felsGrPucv-j8y",
    password: "",
    type: "class",
    note: "ওয়েব সাইটের",
    priority: "medium",
  },
  {
    id: "cls-chapter-all",
    title: "অধ্যায় ভিত্তিক সকল মকটেস্ট",
    link: "https://www.youtube.com/playlist?list=PLvsHTr2JeNs2jyIq2WCdbMDzQhp1hNXZN",
    password: "",
    type: "class",
    note: "গুরুত্বপূর্ণ",
    priority: "medium",
  },
  {
    id: "cls-mt25-solution",
    title: "মকটেস্ট ২৫ সমাধান ক্লাস",
    link: "https://youtu.be/UkjmoqxVnZQ",
    password: "",
    type: "class",
    note: "YouTube লিংক",
    priority: "medium",
  },
  {
    id: "pdf-jft",
    title: "JFT এর জন্য সকল পিডিএফ",
    link: "https://drive.google.com/drive/folders/1fyrpcT0u2HrEWu9ldjW7d289_P84Cs-y",
    password: "",
    type: "pdf",
    note: "Google Drive",
    priority: "low",
  },
  {
    id: "pdf-xyz-stories",
    title: "Irodori X, Y, Z all stories",
    link: "https://drive.google.com/drive/folders/1vH_y3eNOm8usW5hT-g0fjBR0oSqJLKv3",
    password: "",
    type: "pdf",
    note: "সব লেশন স্টোরি",
    priority: "low",
  },
  {
    id: "listen-y",
    title: "Y book all kaiwa listening",
    link: "https://youtube.com/playlist?list=PLZZ5MrEgbcL34n8jBySIwtwk5FjWKSsAE&si=fPPxT4QCHdGn9X99",
    password: "",
    type: "listening",
    note: "",
    priority: "low",
  },
  {
    id: "listen-x",
    title: "X book all kaiwa listening",
    link: "https://youtube.com/playlist?list=PLZZ5MrEgbcL01VcvUgxd_QQKHUYKfoMQU&si=aziJjVGBCqAZNlqo",
    password: "",
    type: "listening",
    note: "",
    priority: "low",
  },
  {
    id: "listen-z",
    title: "Z book all kaiwa listening",
    link: "https://youtube.com/playlist?list=PLZZ5MrEgbcL3ub3X9sFv2wu2c4rreeNaa&si=Zch2PtuLpdya0DOD",
    password: "",
    type: "listening",
    note: "",
    priority: "low",
  },
  {
    id: "cls-x-grammar-1",
    title: "X Grammar - 1",
    link: "https://1-x-grammar.netlify.app/",
    password: "",
    type: "class",
    note: "X বইয়ের গ্রামার",
    priority: "medium",
  },
  {
    id: "cls-x-grammar-2",
    title: "X Grammar - 2",
    link: "https://2-x-grammar.netlify.app/",
    password: "",
    type: "class",
    note: "X বইয়ের গ্রামার",
    priority: "medium",
  },
  {
    id: "cls-z-grammar-1",
    title: "Z Grammar - 1",
    link: "https://1-z-grammar-irodorivai.netlify.app/",
    password: "",
    type: "class",
    note: "Z বইয়ের গ্রামার",
    priority: "medium",
  },
  {
    id: "cls-z-grammar-2",
    title: "Z Grammar - 2",
    link: "https://2-grammar-z-irodorvai.netlify.app/",
    password: "",
    type: "class",
    note: "Z বইয়ের গ্রামার",
    priority: "medium",
  },
  {
    id: "cls-z-grammar-3",
    title: "Z Grammar - 3",
    link: "https://3-z-grammar.netlify.app/",
    password: "",
    type: "class",
    note: "Z বইয়ের গ্রামার",
    priority: "medium",
  },
  {
    id: "cls-verb-forms",
    title: "Verb Forms - 10",
    link: "https://10-verb-forms-irodorivai.netlify.app/",
    password: "",
    type: "class",
    note: "ভার্ব ফর্মস",
    priority: "medium",
  },
  {
    id: "cls-script-3",
    title: "Script - 3",
    link: "https://3-script-irodori-vai.netlify.app/",
    password: "",
    type: "class",
    note: "স্ক্রিপ্ট অনুশীলন",
    priority: "medium",
  },
  {
    id: "cls-script-vocab",
    title: "Script Vocabulary",
    link: "https://update-scipt-vocabulary.netlify.app/",
    password: "",
    type: "class",
    note: "স্ক্রিপ্ট ভোকাবুলারি",
    priority: "medium",
  },
  {
    id: "mt-midnight",
    title: "মিড নাইট সারপ্রাইজ টেস্ট",
    link: "https://update-short-test.netlify.app/",
    password: "",
    type: "mocktest",
    note: "১৬ টি গুরুত্বপূর্ণ প্রশ্ন। ভেরি ইম্পর্ট্যান্ট",
    priority: "high",
  },
  {
    id: "mt-picture",
    title: "Picture Test",
    link: "https://update-picture-test.netlify.app/",
    password: "",
    type: "mocktest",
    note: "ছবি দেখে উত্তর দিতে হবে",
    priority: "high",
  },
  {
    id: "kanji-1",
    title: "কাঞ্জি টেস্ট - ১",
    link: "https://irodoribhaikanjitheraphy1.netlify.app/",
    password: "",
    type: "kanji",
    note: "প্রথম কাঞ্জি টেস্ট",
    priority: "high",
  },
  {
    id: "kanji-2",
    title: "কাঞ্জি টেস্ট - ২",
    link: "https://irodoribhaiybook.netlify.app/",
    password: "",
    type: "kanji",
    note: "দ্বিতীয় কাঞ্জি টেস্ট",
    priority: "high",
  },
  {
    id: "kanji-3",
    title: "কাঞ্জি টেস্ট - ৩",
    link: "https://irodorivaizbookkanjitest.netlify.app/",
    password: "",
    type: "kanji",
    note: "তৃতীয় কাঞ্জি টেস্ট",
    priority: "high",
  },
  {
    id: "kanji-7",
    title: "কাঞ্জি টেস্ট - ৭",
    link: "https://7-kanji-test-irodorivai.netlify.app/",
    password: "",
    type: "kanji",
    note: "",
    priority: "high",
  },
  {
    id: "kanji-8",
    title: "কাঞ্জি টেস্ট - ৮",
    link: "https://8-kanji-irodorivai.netlify.app/",
    password: "",
    type: "kanji",
    note: "",
    priority: "high",
  },
  {
    id: "expr-4",
    title: "Expression - 4",
    link: "https://4-expression-irodorivai.netlify.app/",
    password: "",
    type: "expression",
    note: "",
    priority: "medium",
  },
  {
    id: "expr-5",
    title: "Expression - 5",
    link: "https://5-expression-irodorivai.netlify.app/",
    password: "",
    type: "expression",
    note: "",
    priority: "medium",
  },
  {
    id: "expr-6",
    title: "Expression - 6",
    link: "https://6-expression-irodorivai.netlify.app/",
    password: "",
    type: "expression",
    note: "",
    priority: "medium",
  },
  {
    id: "expr-7",
    title: "Expression - 7",
    link: "https://7-expression-irodorivai.netlify.app/",
    password: "",
    type: "expression",
    note: "",
    priority: "medium",
  },
  {
    id: "expr-8",
    title: "Expression - 8",
    link: "https://8-expression-irodorivai.netlify.app/",
    password: "",
    type: "expression",
    note: "",
    priority: "medium",
  },
];

export const JFT_PASSWORD = "irodoribhai1";

export const typeLabels: Record<string, string> = {
  mocktest: "মকটেস্ট",
  coupon: "কুপন টেস্ট",
  class: "ক্লাস",
  pdf: "পিডিএফ",
  listening: "লিসেনিং",
  kanji: "কাঞ্জি",
  expression: "এক্সপ্রেশন",
};

export const typeIcons: Record<string, string> = {
  mocktest: "📝",
  coupon: "🎟️",
  class: "🎬",
  pdf: "📄",
  listening: "🎧",
  kanji: "📖",
  expression: "💬",
};
